name: Publish to crates.io

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  pre-publish:
    name: Pre-publish Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run Final Tests
        run: cargo test --all-features

  publish:
    name: Publish Crates
    needs: pre-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@v1.0.4
        id: auth

      - name: Publish vyn-relay
        run: cargo publish -p vyn-relay --token ${{ steps.auth.outputs.token }}

      - name: Wait for vyn-relay to be indexed
        run: sleep 40

      - name: Publish vyn-core
        run: cargo publish -p vyn-core --token ${{ steps.auth.outputs.token }}

      - name: Wait for vyn-core to be indexed
        run: sleep 40

      - name: Publish vyn-cli
        run: cargo publish -p vyn-cli --token ${{ steps.auth.outputs.token }}
