name: Publish to crates.io

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  pre-publish:
    name: Pre-publish Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run Final Tests
        run: cargo test --all-features

  publish:
    name: Publish Crate
    needs: pre-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@v0.1.3
        id: auth

      - name: Cargo Publish
        run: cargo publish --token ${{ steps.auth.outputs.token }}
